# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AutoTrader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AutoTrader
	pod 'Reusable', '4.1.2'
	pod 'ObjectMapper', '~> 4.4.2'
	pod 'Charts', '4.1.0'
	pod 'SimpleLineChart', '0.0.2'
	pod 'DatePicker', '1.3.1'

  target 'AutoTraderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AutoTraderUITests' do
    # Pods for testing
  end

end
